### ISSUE TITLE
a few macbook and/or retina issues

### ISSUE THREAD

**Issue by honestbleeps** [twolfson/google-music-webkit#3]
Thanks for this, it's awesome!  If you prefer I break this up into separate issues let me know... I found a few issues on Macbook that maybe I can take a stab at fixing sometime if you can't get to it.

- I can't Cmd-Q to quit

- It doesn't show up as an app when cmd-tabbing - may just be a node webkit setting, and may be intentional on your part... might be good to make this an option? I prefer to get to it via cmd-tab if possible - i rarely use the toolbar.

- toolbar icon size is goofy on first start, probably due to retina display: http://puu.sh/dh5ec/5ac960d2ba.png

- upon change of state, toolbar icon is a better size, but still seems not quite right. probably also retina related: http://puu.sh/dh5iA/3864aa4691.png

I really appreciate the work you've put into this, I know it's simple-ish, but the benefit is huge for those of us who don't want google music to run as a tab, and who want media key shortcuts, so thanks!

**Comment by twolfson** [comment]
Closed due to inactivity and deprecation of project in favor of:

https://github.com/twolfson/google-music-electron
