### ISSUE TITLE
Can't play music

### ISSUE THREAD

**Issue by wmertens** [twolfson/google-music-webkit#5]
I've followed the instructions and the window with GM comes up nicely, but I can't play any songs.

I tried allowing all plugins, no difference. It works fine in a Chrome window.

The only hint I have is that it can't find require on line 1...

**Comment by twolfson** [comment]
What's the failed require message say? Also does Google Music have any prompt about requiring Flash to be enabled?

**Comment by wmertens** [comment]
By looking at the terminal I noticed that the require error only happens when I open up the console, so it may not be related. This is the start log, notice the time stamps, the last line only shows when opening the console:

```
> nw .

[82989:0505/112345:INFO:CONSOLE(10)] "", source: file:///Users/wmertens/Documents/AeroFS/Projects/google-music-webkit/lib/index.js (10)
[82989:0505/112346:INFO:CONSOLE(38)] ""No cast extension found"", source: https://www.gstatic.com/cv/js/sender/v1/cast_sender.js (38)
[82989:0505/112421:INFO:CONSOLE(1)] "Uncaught ReferenceError: require is not defined", source:  (1)
```

There are no errors displayed on the play page, except that it's skipping song after song (`Couldn't play <song name>. Skipped ahead.`) followed by a `Can't reach Google Play` which weird since the page loads just fine.

**Comment by twolfson** [comment]
Do you have any of the Labs settings enabled for your account?

**Comment by wmertens** [comment]
I turned all the lab settings off, no change.

I should probably specify I'm on a Mac, using nw 0.12.

**Comment by twolfson** [comment]
Hmmm, very strange. Can you navigate to youtube.com and see if videos will playback?

**Comment by twolfson** [comment]
Google released a new UI today that is breaking the current application and seems to be causing issues with `nw.js`. It's possible that when we fix it, this problem might be fixed but I have no idea.

**Comment by twolfson** [comment]
We had another release since this issue was opened. More importantly though, this project has been deprecated and we now prefer using `electron`:

https://github.com/twolfson/google-music-electron
